name: Version bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    # ❗ захист від нескінченного циклу
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sync with remote
        run: |
          git pull origin main --rebase

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "chore: bump version [skip ci]" || echo "No changes"
          git push origin main
